.TH "Joueur" 3 "Mon Jan 29 2018" "Version 0.1" "Quizz'Vit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Joueur \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBpseudo\fP [10]"
.br
.ti -1c
.RI "int \fBmode\fP"
.br
.ti -1c
.RI "int \fBse\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Quizz'Vit from the source code\&.
